apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "trow.fullname" . }}-admission-create
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "trow.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry
spec:
{{- if .Capabilities.APIVersions.Has "batch/v1alpha1" }}
  ttlSecondsAfterFinished: 0
{{- end }}
  template:
    metadata:
      name: {{ include "trow.fullname" . }}-admission-create
      labels:
        {{- include "trow.labels" . | nindent 8 }}
        app.kubernetes.io/component: registry
    spec:
      containers:
        - name: create
          image: {{ .Values.trow.validation.patch.image.image }}
          imagePullPolicy: {{ .Values.trow.validation.patch.image.pullPolicy }}
          args:
            - create
            - --host={{ include "trow.fullname" . }}-admission,{{ include "trow.fullname" . }}-admission.$(POD_NAMESPACE).svc
            - --namespace=$(POD_NAMESPACE)
            - --secret-name={{ include "trow.fullname" . }}-tls
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            allowPrivilegeEscalation: false
      restartPolicy: OnFailure
      serviceAccountName: {{ include "trow.fullname" . }}-tls-patch
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
        fsGroup: 2000
