apiVersion: v1
kind: Service
metadata:
  name: {{ include "trow.fullname" . }}
  labels:
    {{- include "trow.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "ClusterIP") (not (empty .Values.service.clusterIP)) }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - port: 443
      targetPort: https
      name: https
    {{- if semverCompare ">=1.20" .Capabilities.KubeVersion.Version }}
      appProtocol: https
    {{- end }}
  selector:
    {{- include "trow.selectorLabels" . | nindent 4 }}
